/**
 * Configurações globais do projeto VoltchZ
 */

export const CONFIG = {
    ASSETS: {
        CLIENTS: [
            'static/clientes/cliente-1.webp',
            'static/clientes/cliente-2.webp',
            'static/clientes/cliente-3.webp',
            'static/clientes/cliente-4.webp',
            'static/clientes/cliente-5.webp',
            'static/clientes/cliente-6.webp',
            'static/clientes/cliente-7.webp',
            'static/clientes/cliente-8.webp',
            'static/clientes/cliente-9.webp',
            'static/clientes/cliente-10.webp',
            'static/clientes/cliente-11.webp',
            'static/clientes/cliente-12.webp',
            'static/clientes/cliente-13.webp',
            'static/clientes/cliente-14.webp',
            'static/clientes/cliente-15.webp',
            'static/clientes/cliente-16.webp',
            'static/clientes/cliente-17.webp',
            'static/clientes/cliente-18.webp',
            'static/clientes/cliente-19.webp',
            'static/clientes/cliente-20.webp',
            'static/clientes/cliente-21.webp',
            'static/clientes/cliente-22.webp',
            'static/clientes/cliente-23.webp',
            'static/clientes/cliente-24.webp',
            'static/clientes/cliente-25.webp',
            'static/clientes/cliente-26.webp',
            'static/clientes/cliente-27.webp',
            'static/clientes/cliente-28.webp',
            'static/clientes/cliente-29.webp',
            'static/clientes/cliente-30.webp',
            'static/clientes/cliente-31.webp',
            'static/clientes/cliente-32.webp',
            'static/clientes/cliente-33.webp',
            'static/clientes/cliente-34.webp',
            'static/clientes/cliente-35.webp',
            'static/clientes/cliente-36.webp',
            'static/clientes/cliente-37.webp',
            'static/clientes/cliente-38.webp',
            'static/clientes/cliente-39.webp',
            'static/clientes/cliente-40.webp',
            'static/clientes/cliente-41.webp',
            'static/clientes/cliente-42.webp',
            'static/clientes/cliente-43.webp',
            'static/clientes/cliente-44.webp',
            'static/clientes/cliente-45.webp',
            'static/clientes/cliente-46.webp',
            'static/clientes/cliente-47.webp',
            'static/clientes/cliente-48.webp',
            'static/clientes/cliente-49.webp',
            'static/clientes/cliente-50.webp',
            'static/clientes/cliente-51.webp',
            'static/clientes/cliente-52.webp',
            'static/clientes/cliente-53.webp',
            'static/clientes/cliente-54.webp',
            'static/clientes/cliente-55.webp',
            'static/clientes/cliente-56.webp',
            'static/clientes/cliente-57.webp',
            'static/clientes/cliente-58.webp',
            'static/clientes/cliente-59.webp',
            'static/clientes/cliente-60.webp',
            'static/clientes/cliente-61.webp',
            'static/clientes/cliente-62.webp',
            'static/clientes/cliente-63.webp',
            'static/clientes/cliente-64.webp',
            'static/clientes/cliente-65.webp',
        ],
        LOGOS: [
            'static/logos-clientes/logo-1.svg',
            'static/logos-clientes/logo-2.png',
            'static/logos-clientes/logo-3.png',
        ],
        DEFAULT_LOGO: 'static/logo.webp'
    },
    ANIMATIONS: {
        AUTOPLAY_HERO: 6000,
        AUTOPLAY_CLIENTS: 5000,
        COUNTER_DURATION: 1800
    },
    CONTACT: {
        WHATSAPP: '5512981039845',
        EMAIL: 'contato@voltchz.com.br'
    }
};