/**
 * Configurações globais do projeto VoltchZ
 */

export const CONFIG = {
    ASSETS: {
        CLIENTS: [
            'static/imagens/CLIENTES/cliente-1.webp',
            'static/imagens/CLIENTES/cliente-2.webp',
            'static/imagens/CLIENTES/cliente-3.webp',
            'static/imagens/CLIENTES/cliente-4.webp',
            'static/imagens/CLIENTES/cliente-5.webp',
            'static/imagens/CLIENTES/cliente-6.webp',
            'static/imagens/CLIENTES/cliente-7.webp',
            'static/imagens/CLIENTES/cliente-8.webp',
            'static/imagens/CLIENTES/cliente-9.webp',
            'static/imagens/CLIENTES/cliente-10.webp',
            'static/imagens/CLIENTES/cliente-11.webp',
            'static/imagens/CLIENTES/cliente-12.webp',
            'static/imagens/CLIENTES/cliente-13.webp',
            'static/imagens/CLIENTES/cliente-14.webp',
            'static/imagens/CLIENTES/cliente-15.webp',
            'static/imagens/CLIENTES/cliente-16.webp',
            'static/imagens/CLIENTES/cliente-17.webp',
            'static/imagens/CLIENTES/cliente-18.webp',
            'static/imagens/CLIENTES/cliente-19.webp',
            'static/imagens/CLIENTES/cliente-20.webp',
            'static/imagens/CLIENTES/cliente-21.webp',
            'static/imagens/CLIENTES/cliente-22.webp',
            'static/imagens/CLIENTES/cliente-23.jpeg',
            'static/imagens/CLIENTES/cliente-24.jpeg',
            'static/imagens/CLIENTES/cliente-25.jpeg',
            'static/imagens/CLIENTES/cliente-26.jpeg',
            'static/imagens/CLIENTES/cliente-27.jpeg',
            'static/imagens/CLIENTES/cliente-28.jpeg',
            'static/imagens/CLIENTES/cliente-29.jpeg',
            'static/imagens/CLIENTES/cliente-30.jpeg',
            'static/imagens/CLIENTES/cliente-31.jpeg',
            'static/imagens/CLIENTES/cliente-32.jpeg',
            'static/imagens/CLIENTES/cliente-33.jpeg',
            'static/imagens/CLIENTES/cliente-34.jpeg',
            'static/imagens/CLIENTES/cliente-35.jpeg',
            'static/imagens/CLIENTES/cliente-36.jpeg',
            'static/imagens/CLIENTES/cliente-37.jpeg',
            'static/imagens/CLIENTES/cliente-38.jpeg',
            'static/imagens/CLIENTES/cliente-39.jpeg',
            'static/imagens/CLIENTES/cliente-40.jpeg',
            'static/imagens/CLIENTES/cliente-41.jpeg',
            'static/imagens/CLIENTES/cliente-42.jpeg',
            'static/imagens/CLIENTES/cliente-43.jpeg',
            'static/imagens/CLIENTES/cliente-44.jpeg',
            'static/imagens/CLIENTES/cliente-45.jpeg',
            'static/imagens/CLIENTES/cliente-46.jpeg',
            'static/imagens/CLIENTES/cliente-47.jpeg',
            'static/imagens/CLIENTES/cliente-48.jpeg',
            'static/imagens/CLIENTES/cliente-49.jpeg',
            'static/imagens/CLIENTES/cliente-50.jpeg',
            'static/imagens/CLIENTES/cliente-51.jpeg',
            'static/imagens/CLIENTES/cliente-52.jpeg',
            'static/imagens/CLIENTES/cliente-53.jpeg',
            'static/imagens/CLIENTES/cliente-54.jpeg',
            'static/imagens/CLIENTES/cliente-55.jpeg',
            'static/imagens/CLIENTES/cliente-56.jpeg',
            'static/imagens/CLIENTES/cliente-57.jpeg',
            'static/imagens/CLIENTES/cliente-58.jpeg',
            'static/imagens/CLIENTES/cliente-59.jpeg',
            'static/imagens/CLIENTES/cliente-60.jpeg',
            'static/imagens/CLIENTES/cliente-61.jpeg',
            'static/imagens/CLIENTES/cliente-62.jpg',
            'static/imagens/CLIENTES/cliente-63.jpg',
            'static/imagens/CLIENTES/cliente-64.jpg',
            'static/imagens/CLIENTES/cliente-65.jpeg',
        ],
        LOGOS: [
            'static/imagens/LOGOS-CLIENTES/logo-1.svg',
            'static/imagens/LOGOS-CLIENTES/logo-2.png',
            'static/imagens/LOGOS-CLIENTES/logo-3.png',
        ],
        DEFAULT_LOGO: 'static/imagens/logo.webp'
    },
    ANIMATIONS: {
        AUTOPLAY_HERO: 6000,
        AUTOPLAY_CLIENTS: 5000,
        COUNTER_DURATION: 1800
    },
    CONTACT: {
        WHATSAPP: '5512981039845',
        EMAIL: 'contato@voltchz.com.br'
    }
};
